import '@testing-library/jest-dom/vitest';
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { beforeEach, expect, it, vi } from 'vitest';
import { MediaVersionsDialogHost } from './MediaVersionsDialog';
import { openMediaVersions } from '@/services/mediaVersions';
const api = vi.hoisted(() => ({ get: vi.fn(), post: vi.fn(), refresh: vi.fn() }));
vi.mock('@/services/api', () => ({ apiClient: api }));
vi.mock('@/realtime/realtimeRefreshBus', () => ({ triggerShootDetailRefresh: api.refresh }));
vi.mock('@/components/studio/v4/StudioImage', () => ({ StudioImage: () => null }));
beforeEach(() => { vi.clearAllMocks(); api.get.mockResolvedValue({ data: { data: [], current_version: 3 } }); api.post.mockResolvedValue({ data: {} }); });
it('keeps version identity and request id after response loss and never treats 100% as published', async () => {
  render(<MemoryRouter><MediaVersionsDialogHost /></MemoryRouter>);
  act(() => openMediaVersions({ shootId: 8, fileId: 12, name: 'Kitchen.jpg' }));
  await screen.findByText(/Current version 3/);
  fireEvent.change(screen.getByLabelText('Upload a saved edit'), { target: { files: [new File(['image'], 'Kitchen.jpg', { type: 'image/jpeg' })] } });
  api.post.mockRejectedValueOnce(new Error('Response lost'));
  fireEvent.click(screen.getByRole('button', { name: 'Upload saved edit' }));
  await screen.findByRole('alert'); const body = api.post.mock.calls[0][1] as FormData;
  api.get.mockResolvedValue({ data: { data: [], current_version: 4 } });
  fireEvent.click(screen.getByRole('button', { name: 'Refresh versions' }));
  await screen.findByText(/Current version 4/);
  fireEvent.click(screen.getByRole('button', { name: 'Upload saved edit' }));
  await screen.findByText(/Upload saved. The current image stays available/);
  expect(api.post.mock.calls[1][1].get('request_id')).toBe(body.get('request_id'));
  expect(api.post.mock.calls[1][1].get('expected_version')).toBe('3');
  expect(api.post.mock.calls[1][2].headers['Content-Type']).toBe('multipart/form-data');
});
it('restoration retries preserve the reviewed version and display explicit conflict choices', async () => {
  const versions = [{ id: 'old', status: 'archived', version: 1, created_at: '2026-10-03' }, { id: 'competing', status: 'conflict', created_at: '2026-10-03' }];
  api.get.mockResolvedValue({ data: { data: versions, current_version: 3 } });
  render(<MemoryRouter initialEntries={['/dashboard?editingShootId=8&editingFileId=12']}><MediaVersionsDialogHost /></MemoryRouter>);
  await screen.findByRole('button', { name: 'Replace latest (v3)' });
  expect(screen.getByRole('button', { name: 'Save as copy' })).toBeVisible();
  api.post.mockRejectedValueOnce(new Error('Response lost'));
  fireEvent.click(screen.getByRole('button', { name: 'Restore as new version' })); await screen.findByRole('alert');
  const body = api.post.mock.calls[0][1];
  fireEvent.click(screen.getByRole('button', { name: 'Restore as new version' }));
  await waitFor(() => expect(api.post).toHaveBeenCalledTimes(2)); expect(api.post.mock.calls[1][1]).toEqual(body);
});
