import { useCallback, useEffect, useRef, useState, type CSSProperties, type PointerEvent } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';
import { Switch } from '@/components/ui/switch';
import { StudioImage } from '@/components/studio/v4/StudioImage';
import type { PhotoEditRecipe, V4Region } from '@/components/studio/v4/types';
import { clampUnit, containRect, regionFromPoints } from './workspaceLogic';
import { customPhotoTitles, type CustomPhotoTool } from './photoEditTools';
import { studioWorkspaceService } from '@/services/studioWorkspaceService';

export function CustomPhotoControls({ workspaceId, tool, recipe, setRecipe, imageUrl, disabled }: {
  workspaceId: string; tool: CustomPhotoTool; recipe: PhotoEditRecipe; setRecipe: (recipe: PhotoEditRecipe) => void; imageUrl?: string; disabled: boolean;
}) {
  const [area, setArea] = useState<'crop' | 'blur' | 'pin' | 'boundary' | null>(null);
  const [band, setBand] = useState<keyof NonNullable<PhotoEditRecipe['color']>>('red');
  const [uploading, setUploading] = useState(false);
  const [uploadError, setUploadError] = useState('');
  const latest = useRef({ recipe, workspaceId });
  latest.current = { recipe, workspaceId };
  const mounted = useRef(true);
  useEffect(() => { mounted.current = true; return () => { mounted.current = false; }; }, []);
  const sliders = (fields: [keyof PhotoEditRecipe, string, number, number, number?][]) => fields.map(([key, label, min, max, step]) => <label className="v4-slider-field" key={key}><span>{label}<output>{Number(recipe[key] ?? 0)}</output></span><input aria-label={label} type="range" min={min} max={max} step={step ?? 1} style={{ '--slider-progress': `${(Number(recipe[key] ?? 0) - min) / (max - min) * 100}%` } as CSSProperties} disabled={disabled} value={Number(recipe[key] ?? 0)} onChange={event => setRecipe({ ...recipe, [key]: Number(event.target.value) })} /></label>);
  const selectArea = (kind: NonNullable<typeof area>, label: string, count = 0, limit = 1) => <Button variant="outline" disabled={disabled || !imageUrl || count >= limit} onClick={() => setArea(kind)}>{label}</Button>;
  const regions = tool === 'privacy' ? recipe.blur ?? [] : tool === 'marks' ? recipe.marks ?? [] : recipe.crop ? [recipe.crop] : [];
  return <div className="v4-custom-controls">
    <h2>{customPhotoTitles[tool]}</h2>
    {tool === 'light' && sliders([['exposure', 'Exposure', -2, 2, .1], ['contrast', 'Contrast', -100, 100], ['temperature', 'Temperature', -100, 100], ['tint', 'Tint', -100, 100], ['saturation', 'Saturation', -100, 100]])}
    {tool === 'tone' && sliders([['highlights', 'Highlights', -100, 100], ['shadows', 'Shadows', -100, 100], ['whites', 'Whites', -100, 100], ['blacks', 'Blacks', -100, 100]])}
    {tool === 'color' && <><label className="v4-field">Color range<select disabled={disabled} value={band} onChange={event => setBand(event.target.value as typeof band)}>{['red', 'orange', 'yellow', 'green', 'aqua', 'blue', 'purple', 'magenta'].map(value => <option key={value} value={value}>{value[0].toUpperCase() + value.slice(1)}</option>)}</select></label>{(['hue', 'saturation', 'lightness'] as const).map(key => <label className="v4-slider-field" key={key}><span>{key[0].toUpperCase() + key.slice(1)}<output>{recipe.color?.[band]?.[key] ?? 0}</output></span><input aria-label={`${band} ${key}`} type="range" min={key === 'hue' ? -30 : -100} max={key === 'hue' ? 30 : 100} disabled={disabled} value={recipe.color?.[band]?.[key] ?? 0} style={{ '--slider-progress': `${((recipe.color?.[band]?.[key] ?? 0) + (key === 'hue' ? 30 : 100)) / (key === 'hue' ? 60 : 200) * 100}%` } as CSSProperties} onChange={event => setRecipe({ ...recipe, color: { ...recipe.color, [band]: { ...recipe.color?.[band], [key]: Number(event.target.value) } } })} /></label>)}<p>Change only the selected color range. Review natural materials against the original.</p></>}
    {tool === 'detail' && <>{sliders([['sharpen', 'Sharpen', 0, 30], ['denoise', 'Smooth noise', 0, 3]])}<p>Keep sharpening subtle to preserve natural textures.</p></>}
    {tool === 'crop' && <>{selectArea('crop', recipe.crop ? 'Change crop' : 'Select crop')}<label className="v4-field">Rotate<select disabled={disabled} value={recipe.rotation ?? 0} onChange={event => setRecipe({ ...recipe, rotation: Number(event.target.value) })}>{[0, 90, 180, 270].map(value => <option key={value} value={value}>{value}° clockwise</option>)}</select></label><label className="v4-switch-field">Flip horizontally<Switch disabled={disabled} checked={recipe.flip ?? false} onCheckedChange={flip => setRecipe({ ...recipe, flip })} /></label></>}
    {tool === 'privacy' && <><p>Draw an area over a face, plate, or sensitive detail. Selected areas are pixelated in the saved photo.</p>{selectArea('blur', 'Select privacy area', regions.length, 20)}</>}
    {tool === 'marks' && <><p>Add labels or rectangular property boundaries. Confirm all positions before delivery.</p>{selectArea('pin', 'Place a pin', regions.length, 30)}{selectArea('boundary', 'Draw boundary', regions.length, 30)}</>}
    {tool === 'brand' && <><label className="v4-field">Photo caption<input disabled={disabled} maxLength={100} placeholder="Brand name or disclosure" value={recipe.caption ?? ''} onChange={event => setRecipe({ ...recipe, caption: event.target.value })} /></label><Button variant="outline" disabled={disabled} onClick={() => setRecipe({ ...recipe, caption: 'Virtually staged' })}>Add staging disclosure</Button><label className="v4-field">Brand logo<input type="file" accept="image/png,image/jpeg,image/webp" disabled={disabled || uploading} onChange={event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 2 * 1024 * 1024) { setUploadError('Choose a logo under 2 MB.'); return; } setUploading(true); setUploadError(''); void studioWorkspaceService.uploadPhotoLogo(workspaceId, file).then(asset => { if (mounted.current && latest.current.workspaceId === workspaceId) setRecipe({ ...latest.current.recipe, logo: { id: asset.id, x: .03, y: .03, width: .18, opacity: 85 } }); }).catch(() => setUploadError('The logo could not upload. Use a PNG, JPEG, or WebP under 2 MB.')).finally(() => setUploading(false)); }} /></label>{uploading && <p>Uploading logo…</p>}{uploadError && <p role="alert">{uploadError}</p>}{recipe.logo && <><label className="v4-field">Logo position<select disabled={disabled} value={`${recipe.logo.x},${recipe.logo.y}`} onChange={event => { const [x, y] = event.target.value.split(',').map(Number); setRecipe({ ...recipe, logo: { ...recipe.logo!, x, y } }); }}><option value="0.03,0.03">Top left</option><option value="0.78,0.03">Top right</option><option value="0.03,0.8">Bottom left</option><option value="0.78,0.8">Bottom right</option></select></label>{(['width', 'opacity'] as const).map(key => <label className="v4-slider-field" key={key}><span>{key === 'width' ? 'Logo size' : 'Logo opacity'}<output>{Math.round(key === 'width' ? recipe.logo!.width * 100 : recipe.logo!.opacity ?? 85)}%</output></span><input aria-label={key === 'width' ? 'Logo size' : 'Logo opacity'} type="range" min={key === 'width' ? 1 : 0} max={key === 'width' ? 50 : 100} disabled={disabled} style={{ '--slider-progress': `${key === 'width' ? (recipe.logo!.width * 100 - 1) / 49 * 100 : recipe.logo!.opacity ?? 85}%` } as CSSProperties} value={key === 'width' ? recipe.logo!.width * 100 : recipe.logo!.opacity ?? 85} onChange={event => setRecipe({ ...recipe, logo: { ...recipe.logo!, [key]: Number(event.target.value) / (key === 'width' ? 100 : 1) } })} /></label>)}<Button variant="outline" disabled={disabled} onClick={() => { const next = { ...recipe }; delete next.logo; setRecipe(next); }}>Remove logo</Button></>}</>}
    {regions.map((region, index) => <div className="v4-custom-region" key={index}><span>{tool === 'crop' ? 'Crop' : tool === 'privacy' ? `Privacy area ${index + 1}` : `Annotation ${index + 1}`}</span><Button size="sm" variant="ghost" disabled={disabled} onClick={() => { const next = { ...recipe }; if (tool === 'crop') delete next.crop; else if (tool === 'privacy') next.blur = (recipe.blur ?? []).filter((_, i) => i !== index); else next.marks = (recipe.marks ?? []).filter((_, i) => i !== index); setRecipe(next); }}>Remove</Button><small>{Math.round(region.width * 100)}% × {Math.round(region.height * 100)}%</small></div>)}
    {area && imageUrl && <PhotoAreaPicker key={area} mode={area} imageUrl={imageUrl} onClose={() => setArea(null)} onSelect={(region, label) => { const next = { ...recipe }; if (area === 'crop') next.crop = region; else if (area === 'blur') next.blur = [...(recipe.blur ?? []), region]; else next.marks = [...(recipe.marks ?? []), { ...region, kind: area, label }]; setRecipe(next); setArea(null); }} />}
  </div>;
}

/** Normalize pointer coordinates against the contained image, excluding letterboxing. */
function PhotoAreaPicker({ mode, imageUrl, onClose, onSelect }: { mode: string; imageUrl: string; onClose: () => void; onSelect: (region: V4Region, label: string) => void }) {
  const surfaceObserver = useRef<ResizeObserver | null>(null);
  const start = useRef<{ x: number; y: number } | null>(null);
  const [size, setSize] = useState({ width: 1, height: 1 });
  const [imageSize, setImageSize] = useState({ width: 1, height: 1 });
  const [region, setRegion] = useState<V4Region>();
  const [label, setLabel] = useState('');
  const contained = containRect(size.width, size.height, imageSize.width, imageSize.height);
  const rect = { ...contained, left: contained.x, top: contained.y };
  const attachSurface = useCallback((element: HTMLDivElement | null) => {
    surfaceObserver.current?.disconnect(); surfaceObserver.current = null;
    if (!element) return;
    const update = () => setSize({ width: element.clientWidth, height: element.clientHeight }); update();
    if (typeof ResizeObserver !== 'undefined') { surfaceObserver.current = new ResizeObserver(update); surfaceObserver.current.observe(element); }
  }, []);
  const point = (event: PointerEvent<HTMLDivElement>) => { const bounds = event.currentTarget.getBoundingClientRect(); return { x: clampUnit((event.clientX - bounds.left - rect.left) / rect.width), y: clampUnit((event.clientY - bounds.top - rect.top) / rect.height) }; };
  return <Dialog open onOpenChange={open => { if (!open) onClose(); }}><DialogContent className="v4-editor-dialog v4-area-dialog"><DialogTitle>{mode === 'crop' ? 'Select crop' : mode === 'blur' ? 'Select privacy area' : mode === 'pin' ? 'Place a pin' : 'Draw boundary'}</DialogTitle><DialogDescription>Drag across the photo to select an area. Adjust the coordinates below for precise placement.</DialogDescription><div ref={attachSurface} className="v4-area-surface" onPointerDown={event => { if (event.button !== 0) return; const bounds = event.currentTarget.getBoundingClientRect(); const x = event.clientX - bounds.left, y = event.clientY - bounds.top; if (x < rect.left || y < rect.top || x > rect.left + rect.width || y > rect.top + rect.height) return; start.current = point(event); event.currentTarget.setPointerCapture(event.pointerId); }} onPointerMove={event => { if (start.current) setRegion(regionFromPoints(start.current, point(event))); }} onPointerUp={event => { if (start.current) setRegion(regionFromPoints(start.current, point(event))); start.current = null; }} onPointerCancel={() => { start.current = null; }}><StudioImage src={imageUrl} alt="Photo area selection" loading="eager" onLoad={event => setImageSize({ width: event.currentTarget.naturalWidth, height: event.currentTarget.naturalHeight })} />{region && <span className="v4-area-box" style={{ left: rect.left + region.x * rect.width, top: rect.top + region.y * rect.height, width: region.width * rect.width, height: region.height * rect.height }} />}</div><div className="v4-area-coordinates">{(['x', 'y', 'width', 'height'] as const).map(key => <label key={key}>{key}<input aria-label={`Area ${key}`} type="number" min={key === 'x' || key === 'y' ? 0 : 1} max={100} value={Math.round((region?.[key] ?? (key === 'width' || key === 'height' ? .25 : 0)) * 100)} onChange={event => { const next = { x: 0, y: 0, width: .25, height: .25, ...region, [key]: clampUnit(Number(event.target.value) / 100) }; next.x = Math.min(next.x, 1 - next.width); next.y = Math.min(next.y, 1 - next.height); setRegion(next); }} /></label>)}</div>{(mode === 'pin' || mode === 'boundary') && <label className="v4-field">Label<input maxLength={40} value={label} onChange={event => setLabel(event.target.value)} /></label>}<Button data-variant="primary" disabled={!region || region.width <= 0 || region.height <= 0} onClick={() => { if (region) onSelect(region, label); }}>Use this area</Button></DialogContent></Dialog>;
}
