import { StudioImage } from './StudioImage';
import { PreviousEdits } from './PreviousEdits';
import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ChevronDown, Clock3, Film, FolderOpen, History, ImagePlus, Layers, Play, Search, Sparkles, Video } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { V4_PRESETS, findPreset } from './presets';
import type { V4Media, V4Preset, V4Workspace } from './types';
import { presetAvailability, type StudioCapabilities } from '@/services/studioProviderService';

export type HomeView = 'home' | 'presets' | 'history';
interface Props {
  capabilities?: StudioCapabilities | null;
  name: string; view: HomeView; onView: (view: HomeView) => void; mode: 'studio' | 'image' | 'video'; onMode: (mode: 'studio' | 'image' | 'video') => void;
  media: V4Media[]; label: string; preset: V4Preset; onPreset: (preset: V4Preset) => void;
  onMedia: () => void; onStart: (prompt: string, preset?: V4Preset) => void; busy: boolean;
  workspaces: V4Workspace[]; onResume: (id: string) => void; onRefresh: () => void;
}
const stateLabel = (s: V4Workspace['status']) => ({ draft: 'Draft', preparing: 'Preparing frames', ready: 'Frames ready', generating: 'Generating', completed: 'Ready', failed: 'Needs attention', cancelled: 'Cancelled' })[s];
export function StudioHome(p: Props) {
  const [prompt, setPrompt] = useState('');
  const [filter, setFilter] = useState('Most used');
  const [search, setSearch] = useState('');
  const [historyFilter, setHistoryFilter] = useState('all');
  const presets = useMemo(() => {
    const frequency = new Map<string, number>(); p.workspaces.forEach(w => frequency.set(w.presetId, (frequency.get(w.presetId) || 0) + 1));
    return V4_PRESETS.filter(v => (p.mode === 'studio' || v.kind === p.mode) && `${v.name} ${v.description}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'Most used' || (filter === 'Recent' ? frequency.has(v.id) : v.tag === filter)))
      .sort((a, b) => filter === 'Recent' ? p.workspaces.findIndex(w => w.presetId === a.id) - p.workspaces.findIndex(w => w.presetId === b.id) : (frequency.get(b.id) || 0) - (frequency.get(a.id) || 0));
  }, [p.mode, p.workspaces, filter, search]);
  const history = p.workspaces.filter(w => (historyFilter === 'all' || (historyFilter === 'active' ? ['preparing', 'generating'].includes(w.status) : w.status === historyFilter)) && `${w.name} ${findPreset(w.presetId).name}`.toLowerCase().includes(search.toLowerCase()));
  const presetCard = (preset: V4Preset) => <button key={preset.id} disabled={!presetAvailability(preset.id, p.capabilities).ready} title={presetAvailability(preset.id, p.capabilities).reason} onClick={() => { p.onPreset(preset); if (p.media.length) p.onStart(prompt, preset); else p.onMedia(); }} className="v4-preset-card group overflow-hidden rounded-2xl border border-border/60 bg-card text-left transition hover:-translate-y-0.5 hover:border-primary/50 focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary disabled:cursor-not-allowed disabled:opacity-60">
    <div className="relative aspect-[1.65] overflow-hidden"><StudioImage src={`/studio-assets/${preset.color}.webp`} alt="" loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/65 via-transparent to-black/10" /><span className="absolute left-3 top-3 rounded-md bg-black/60 px-2 py-1 text-[10px] font-medium text-white">{preset.tag}</span>{preset.kind === 'video' && <span className="absolute bottom-3 right-3 rounded-full bg-white/90 p-2 text-slate-900"><Play size={14} fill="currentColor" /></span>}<h3 className="absolute bottom-3 left-3 text-sm font-medium text-white">{preset.name}</h3></div>
    {p.view === 'presets' && <div className="p-3"><p className="min-h-9 text-xs leading-relaxed text-muted-foreground">{preset.description}</p><p className="mt-2 flex items-center gap-1.5 text-[10px] text-muted-foreground">{preset.kind === 'video' ? <Video size={12} /> : <ImagePlus size={12} />}{preset.kind === 'video' ? 'Video preset' : 'Image preset'}<ArrowRight size={13} className="ml-auto" /></p></div>}
  </button>;
  return <div className={`v4-home mx-auto w-full max-w-[1180px] px-1 pb-6 sm:px-6 ${p.view === 'home' ? 'pt-4 sm:pt-7' : 'pt-3'}`}>
    <div className="relative mb-6 flex items-center justify-center gap-3">
      {p.view !== 'home' && <Button variant="ghost" size="icon" className="absolute left-0" aria-label="Back to Studio" onClick={() => { p.onView('home'); setSearch(''); }}><ArrowLeft size={18} /></Button>}
      <nav aria-label="Media type" className="inline-flex rounded-full bg-muted/40 p-1">{(['studio', 'image', 'video'] as const).map(mode => <button key={mode} onClick={() => p.onMode(mode)} aria-current={p.mode === mode ? 'page' : undefined} className={`rounded-full px-4 py-2 text-sm capitalize transition sm:px-6 ${p.mode === mode ? 'bg-primary text-primary-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'}`}>{mode}</button>)}</nav>
      <Button variant="ghost" size="icon" className="absolute right-0 rounded-full" aria-label="Editing history" onClick={() => { p.onView('history'); setSearch(''); }}><History size={19} /></Button>
    </div>
    {p.view === 'home' ? <>
      <h1 className="mb-7 text-center text-xl font-normal tracking-tight sm:mb-9 sm:text-[28px]">Hey {p.name}! {p.mode === 'video' ? 'let’s bring this property to life.' : p.mode === 'image' ? 'let’s make every photo listing-ready.' : 'what are we editing today?'}</h1>
      <form className="v4-composer rounded-[26px] border border-border bg-card/80 p-4 shadow-[0_12px_50px_-35px_rgba(37,99,235,.45)] sm:p-5" onSubmit={e => { e.preventDefault(); p.onStart(prompt); }}>
        <textarea aria-label="Describe your edit" placeholder={p.mode === 'video' ? 'Create a walkthrough, highlight the best rooms, or make a listing reel…' : 'Enhance photos, stage rooms, or create a property reel…'} value={prompt} onChange={e => setPrompt(e.target.value)} rows={2} className="min-h-20 w-full resize-none border-0 bg-transparent px-1 pt-1 text-base leading-relaxed placeholder:text-muted-foreground focus:outline-none sm:text-lg" />
        <div className="v4-composer-row mt-3 flex items-center gap-2 pb-1"><div className="flex min-w-0 flex-1 items-center gap-2 overflow-x-auto pb-1">
          <button type="button" onClick={p.onMedia} className="flex h-[54px] w-[144px] shrink-0 items-center gap-2 sm:w-auto sm:gap-3 rounded-xl border border-border bg-muted/35 px-3 text-left"><div className="min-w-0 flex-1 sm:max-w-[138px]"><p className="truncate text-sm font-medium leading-tight">{p.media.length ? p.label : 'Select shoot'}</p><p className="mt-1 truncate text-[10px] leading-tight text-muted-foreground sm:text-[11px]">{p.media.length ? `${p.media.length} files selected` : 'Or upload media'}</p></div><ChevronDown size={15} className="shrink-0 text-muted-foreground" /></button>
          {!!p.media.length && <button type="button" onClick={p.onMedia} className="v4-image-stack group/stack flex h-[54px] shrink-0 items-center pr-0 sm:pr-2" aria-label={`View ${p.media.length} selected files`}><span className="relative block h-10 w-[48px] sm:w-[64px] [perspective:200px]">{p.media.slice(0, 3).map((m, i) => <StudioImage key={m.id} src={m.thumbnailUrl} alt="" style={{ left: i * 12, zIndex: 3 - i }} className="absolute top-0 h-10 w-6 sm:w-8 origin-right rounded-md border border-background object-cover shadow-md transition-transform duration-300 [transform:rotateY(-32deg)] group-hover/stack:[transform:rotateY(0deg)] group-focus-visible/stack:[transform:rotateY(0deg)] motion-reduce:transition-none" />)}</span>{p.media.length > 3 && <span className="ml-1 hidden text-xs font-medium sm:inline">+{p.media.length - 3}</span>}</button>}
          <Select value={p.preset.id} onValueChange={v => { if (V4_PRESETS.some(item => item.id === v)) p.onPreset(findPreset(v)); }}><SelectTrigger aria-label="Editing preset" className="h-[54px] w-auto min-w-[44px] shrink-0 gap-0 rounded-xl bg-muted/35 px-2 sm:min-w-[176px] sm:gap-3 sm:px-3 [&>svg]:hidden sm:[&>svg]:block"><div className="flex items-center gap-2"><span className="rounded-lg bg-primary/10 p-2 text-primary">{p.preset.kind === 'video' ? <Film size={16} /> : <Sparkles size={16} />}</span><span className="sr-only sm:not-sr-only"><SelectValue>{p.preset.name}</SelectValue></span></div></SelectTrigger><SelectContent>{V4_PRESETS.filter(v => p.mode === 'studio' || v.kind === p.mode).map(v => <SelectItem key={v.id} value={v.id} disabled={!presetAvailability(v.id, p.capabilities).ready}>{v.name}</SelectItem>)}</SelectContent></Select>
          <Button type="button" variant="ghost" onClick={p.onMedia} className="h-9 w-9 shrink-0 gap-2 rounded-xl px-0 sm:w-auto sm:px-4"><ImagePlus size={18} /><span className="hidden sm:inline">Media</span></Button>
          </div><Button type="submit" disabled={p.busy || !presetAvailability(p.preset.id, p.capabilities).ready} size="icon" className="ml-auto h-11 w-11 shrink-0 rounded-full" aria-label="Continue to editor"><ArrowRight size={21} /></Button>
        </div>
      </form>
    </> : <div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold tracking-tight">{p.view === 'presets' ? 'Find your next edit.' : 'Your editing history'}</h1><p className="mt-1 text-sm text-muted-foreground">{p.view === 'presets' ? 'A starting point for every property.' : 'Every shoot, every version. Pick up where you left off.'}</p></div><div className="relative w-full sm:w-64"><Search size={16} className="absolute left-3 top-3 text-muted-foreground" /><Input className="pl-9" value={search} onChange={e => setSearch(e.target.value)} placeholder={p.view === 'history' ? 'Search shoot or preset…' : 'Search presets…'} aria-label="Search" /></div></div>}
    {p.view !== 'history' && <section className="mt-7 sm:mt-8"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><h2 className="text-lg font-medium">{p.view === 'home' ? 'Create for this shoot' : `${presets.length} presets`}</h2>{p.view === 'home' && <button className="flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground" onClick={() => p.onView('presets')}>View all <ArrowRight size={13} /></button>}</div><div className="flex gap-1 overflow-auto">{['Most used', 'New', 'Popular', 'Recent'].map(f => <button key={f} onClick={() => setFilter(f)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-[11px] ${f === filter ? 'bg-muted text-foreground' : 'text-muted-foreground'}`}>{f}</button>)}</div></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{presets.slice(0, p.view === 'home' ? 8 : undefined).map(presetCard)}</div>{!presets.length && <p className="py-12 text-center text-muted-foreground">No presets match your search.</p>}</section>}
    {p.view !== 'presets' && <section className="mt-8"><div className="mb-4 flex items-center justify-between gap-3"><h2 className="text-lg font-medium">{p.view === 'home' ? 'Recent' : `${history.length} projects`}</h2>{p.view === 'home' ? <button className="flex items-center gap-1 text-xs text-muted-foreground hover:text-foreground" onClick={() => p.onView('history')}>View all <ArrowRight size={13} /></button> : <Select value={historyFilter} onValueChange={setHistoryFilter}><SelectTrigger className="h-9 w-36" aria-label="Filter history"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All projects</SelectItem><SelectItem value="active">In progress</SelectItem><SelectItem value="completed">Ready</SelectItem><SelectItem value="draft">Drafts</SelectItem><SelectItem value="failed">Needs attention</SelectItem></SelectContent></Select>}</div>
      {!history.length ? <div className="flex flex-col items-center justify-center gap-3 rounded-2xl border border-dashed border-border bg-muted/10 px-6 py-8 text-center"><div className="rounded-xl bg-muted p-3"><Layers size={23} className="text-muted-foreground" /></div><div><p className="text-sm font-medium">{p.view === 'history' ? 'No matching projects yet' : 'Your next great edit starts here'}</p><p className="mt-1 text-xs text-muted-foreground">Choose media and a preset. Your edits will be saved here.</p></div><Button variant="outline" size="sm" onClick={p.onMedia}><FolderOpen size={15} className="mr-2" />Choose media</Button></div> : <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{history.slice(0, p.view === 'home' ? 4 : undefined).map(w => <button key={w.id} onClick={() => p.onResume(w.id)} className="overflow-hidden rounded-xl border border-border/60 bg-card text-left transition hover:border-primary/50"><div className="relative aspect-[1.65] bg-muted/20">{w.outputs.find(o => o.kind === 'image')?.url || w.media[0]?.thumbnailUrl ? <StudioImage src={w.outputs.find(o => o.kind === 'image')?.url || w.media[0]?.thumbnailUrl} alt="" className="h-full w-full object-cover" /> : <Layers className="absolute inset-0 m-auto text-muted-foreground" />}<span className="absolute left-2 top-2 flex items-center gap-1 rounded-md bg-black/70 px-2 py-1 text-[10px] text-white">{w.status === 'completed' ? <Check size={10} /> : <Clock3 size={10} />}{stateLabel(w.status)}{w.progress != null && ['generating', 'preparing'].includes(w.status) ? ` · ${Math.round(w.progress)}%` : ''}</span></div><div className="p-3"><h3 className="truncate text-sm font-medium">{w.name}</h3><p className="mt-1 truncate text-[11px] text-muted-foreground">{findPreset(w.presetId).name} · {w.media.length} files</p></div></button>)}</div>}
    </section>}
    {p.view === 'history' && <PreviousEdits />}
  </div>;
}
