
import { InvoiceData } from '@/utils/invoiceUtils';

// Sample invoices data for the accounting dashboard
export const initialInvoices: InvoiceData[] = [
  {
    id: 'INV-001',
    client: 'ABC Properties',
    property: '123 Main Street, Anytown',
    date: '2023-05-15',
    dueDate: '2023-05-30',
    amount: 250.00,
    status: 'paid',
    services: ['Photography', 'Floorplans'],
    paymentMethod: 'Credit Card',
  },
  {
    id: 'INV-002',
    client: 'XYZ Realty',
    property: '456 Park Avenue, Somewhere',
    date: '2023-05-16',
    dueDate: '2023-05-31',
    amount: 350.00,
    status: 'paid',
    services: ['Photography', 'Video', '3D Tour'],
    paymentMethod: 'Credit Card',
  },
  {
    id: 'INV-003',
    client: 'John Smith Homes',
    property: '789 Ocean Drive, Beachtown',
    date: '2023-05-17',
    dueDate: '2023-06-01',
    amount: 300.00,
    status: 'pending',
    services: ['Photography', 'Drone'],
    paymentMethod: 'Pending',
  },
  {
    id: 'INV-004',
    client: 'Coastal Properties',
    property: '101 Forest Lane, Woodland',
    date: '2023-05-18',
    dueDate: '2023-06-02',
    amount: 425.00,
    status: 'overdue',
    services: ['Photography', 'Video', 'Virtual Staging'],
    paymentMethod: 'Pending',
  },
  {
    id: 'INV-005',
    client: 'ABC Properties',
    property: '202 Hill Avenue, Heights',
    date: '2023-05-19',
    dueDate: '2023-06-03',
    amount: 275.00,
    status: 'pending',
    services: ['Photography', 'Floorplans'],
    paymentMethod: 'Pending',
  },
  {
    id: 'INV-006',
    client: 'United Real Estate',
    property: '505 River Road, Lakeside',
    date: '2023-05-20',
    dueDate: '2023-06-04',
    amount: 560.00,
    status: 'paid',
    services: ['Photography', 'Video', 'Aerial', 'Virtual Staging'],
    paymentMethod: 'Bank Transfer',
  },
  {
    id: 'INV-007',
    client: 'Summit Properties',
    property: '807 Mountain View, Highland',
    date: '2023-05-21',
    dueDate: '2023-06-05',
    amount: 325.00,
    status: 'paid',
    services: ['Photography', 'Virtual Tour'],
    paymentMethod: 'PayPal',
  },
  {
    id: 'INV-008',
    client: 'Golden Gate Realty',
    property: '909 Golden Avenue, Westside',
    date: '2023-05-22',
    dueDate: '2023-06-06',
    amount: 290.00,
    status: 'pending',
    services: ['Photography', 'Floor Plan'],
    paymentMethod: 'Pending',
  },
  {
    id: 'INV-009',
    client: 'Modern Homes Agency',
    property: '1010 Modern Lane, Newtown',
    date: '2023-05-23',
    dueDate: '2023-06-07',
    amount: 380.00,
    status: 'overdue',
    services: ['Photography', 'Video', '3D Tour'],
    paymentMethod: 'Pending',
  },
  {
    id: 'INV-010',
    client: 'Luxury Living',
    property: '1212 Luxury Drive, Highend',
    date: '2023-05-24',
    dueDate: '2023-06-08',
    amount: 850.00,
    status: 'pending',
    services: ['Photography', 'Video', 'Aerial', 'Virtual Staging', '3D Tour'],
    paymentMethod: 'Pending',
  },
];
