import { useEffect, useState } from 'react';
import { ChevronLeft, ChevronRight, Download, Send, Wallet } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import type { EditorEarningsDetail } from '@/services/invoiceService';
import { groupEditorPayouts } from './editorBillingWorkspaceUtils';
import type { ResolveEffectiveEditorEarning } from './editorEarningsTypes';
import { formatEditorCurrency as money, formatEditorTimestamp as timestamp } from './editorEarningsUtils';

interface Props {
  detail: EditorEarningsDetail | null; loading: boolean; sending: boolean;
  resolveEffective: ResolveEffectiveEditorEarning;
  onExport: (format: 'csv' | 'excel' | 'pdf') => void;
  onSend: () => void; onMarkPaid: () => void;
}

export function EditorAdminEarningsDetail({ detail, loading, sending, resolveEffective, onExport, onSend, onMarkPaid }: Props) {
  const [tab, setTab] = useState<'ledger' | 'history' | 'rates'>('ledger');
  const [page, setPage] = useState(1);
  const [size, setSize] = useState(10);
  useEffect(() => { setPage(1); }, [detail, tab, size]);
  const items = detail?.line_items || [], groups = groupEditorPayouts(items);
  const count = tab === 'history' ? groups.length : items.length, pages = Math.max(1, Math.ceil(count / size)), safe = Math.min(page, pages);
  const unpaid = items.filter((item) => !item.is_paid);
  return <Card className="flex h-[35.5rem] min-w-0 flex-col overflow-hidden border-border/70">
    <div className="shrink-0 border-b p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate text-base font-semibold">{detail?.editor.name || 'Editor earnings'}</h2><p className="mt-1 truncate text-xs text-muted-foreground">{detail?.editor.email || 'Select an editor to review earnings.'}</p></div><div className="flex gap-2"><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm" disabled={!items.length || loading}><Download className="mr-1 h-3.5 w-3.5" />Export</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={() => onExport('csv')}>CSV</DropdownMenuItem><DropdownMenuItem onSelect={() => onExport('excel')}>Excel</DropdownMenuItem><DropdownMenuItem onSelect={() => onExport('pdf')}>PDF</DropdownMenuItem></DropdownMenuContent></DropdownMenu><Button variant="outline" size="sm" onClick={onSend} disabled={sending || loading}><Send className="mr-1 h-3.5 w-3.5" />Send report</Button></div></div>
      <div className="mt-4 flex flex-wrap gap-x-4 gap-y-2 text-xs text-muted-foreground"><span><b className="text-foreground">{detail?.summary.shoot_count || 0}</b> shoots</span><span><b className="text-foreground">{detail?.summary.service_count || 0}</b> services</span><span><b className="text-foreground">{money(detail?.summary.total_earned)}</b> saved earnings</span><span><b className="text-foreground">{money(detail?.summary.unpaid_amount)}</b> unpaid</span></div>
    </div>
    <div className="flex shrink-0 flex-wrap gap-1 border-b p-2" role="tablist" aria-label="Editor payout detail sections">{[['ledger', 'Completed work'], ['history', 'Payout history'], ['rates', 'Current rates']].map(([key, label]) => <Button key={key} role="tab" size="sm" variant={tab === key ? 'secondary' : 'ghost'} aria-selected={tab === key} onClick={() => setTab(key as typeof tab)}>{label}</Button>)}</div>
    <div className="min-h-0 flex-1 overflow-auto overscroll-contain [scrollbar-gutter:stable]" tabIndex={0} aria-label="Editor payout detail">
      {loading ? <p className="p-8 text-center text-sm text-muted-foreground">Loading editor earnings…</p> : tab === 'rates' ? <div className="divide-y px-4">{detail?.current_rates.service_rates.length ? detail.current_rates.service_rates.map((rate) => <div key={`${rate.service_id}-${rate.service_name}`} className="flex items-center justify-between gap-3 py-3 text-xs"><span>{rate.service_name}</span><strong>{money(rate.rate)} per item</strong></div>) : <p className="py-8 text-sm text-muted-foreground">No explicit rates are configured.</p>}<p className="py-4 text-xs text-muted-foreground">Saved payout snapshots stay unchanged when current rates change. Current rates only estimate lines without a saved rate or payout.</p></div> : tab === 'history' ? <div className="divide-y px-4">{groups.slice((safe - 1) * size, safe * size).map((group) => <details key={group.id} className="py-3 text-xs"><summary className="cursor-pointer"><span className="font-medium">{group.id}</span><span className="ml-3">{money(group.amount)}</span><span className="ml-3 text-muted-foreground">{timestamp(group.paidAt)}</span></summary><div className="mt-3 space-y-2">{group.items.map((item) => <p key={item.id}>{item.service_name} · Shoot #{item.shoot_id} · {money(item.payout_amount)}</p>)}</div></details>)}{!groups.length && <p className="py-8 text-center text-sm text-muted-foreground">No paid records match the current filters.</p>}</div> : <table className="w-full min-w-[30rem] text-left text-xs"><thead className="sticky top-0 bg-card text-muted-foreground"><tr>{['Service / shoot', 'Qty', 'Rate', 'Payout', 'Completed'].map((name) => <th key={name} className="border-b px-3 py-3 font-medium">{name}</th>)}</tr></thead><tbody>{items.slice((safe - 1) * size, safe * size).map((item) => { const value = resolveEffective(item); return <tr key={item.id} className="border-b"><td className="px-3 py-3"><p className="font-medium">{item.service_name}</p><p className="mt-1 text-[11px] text-muted-foreground">#{item.shoot_id} · {item.client?.name || 'Unknown client'}</p><p className="mt-1 text-[11px] text-muted-foreground">{item.shoot?.address || 'Address unavailable'}</p><Badge variant="outline" className="mt-2 text-[10px]">{item.is_paid ? 'Paid' : 'Unpaid'}</Badge></td><td className="px-3 py-3">{item.quantity_snapshot}</td><td className="whitespace-nowrap px-3 py-3">{money(value.rate)}</td><td className="px-3 py-3"><strong className="whitespace-nowrap">{money(value.payout)}</strong>{value.isFallback && <p className="mt-1 text-[10px] text-amber-600 dark:text-amber-300">Current-rate estimate</p>}</td><td className="px-3 py-3 text-muted-foreground">{timestamp(item.completed_at)}</td></tr>; })}{!items.length && <tr><td colSpan={5} className="p-8 text-center text-muted-foreground">No earnings match the current filters.</td></tr>}</tbody></table>}
    </div>
    <div className="shrink-0 border-t p-3"><div className="flex flex-wrap items-center justify-between gap-2 text-[11px] text-muted-foreground"><span>{tab === 'rates' ? 'Current service rates' : `${count ? (safe - 1) * size + 1 : 0}–${Math.min(safe * size, count)} of ${count}`}</span>{tab !== 'rates' && <div className="flex items-center gap-2"><select aria-label="Editor detail rows per page" value={size} onChange={(event) => setSize(Number(event.target.value))} className="h-7 rounded-md border bg-background px-1"><option value={10}>10 rows</option><option value={20}>20 rows</option></select><Button variant="outline" size="icon" className="h-7 w-7" aria-label="Previous editor detail page" disabled={safe === 1} onClick={() => setPage(safe - 1)}><ChevronLeft className="h-3 w-3" /></Button><span>{safe}/{pages}</span><Button variant="outline" size="icon" className="h-7 w-7" aria-label="Next editor detail page" disabled={safe === pages} onClick={() => setPage(safe + 1)}><ChevronRight className="h-3 w-3" /></Button></div>}</div><Button className="mt-3 w-full" size="sm" onClick={onMarkPaid} disabled={!unpaid.length || loading}><Wallet className="mr-2 h-4 w-4" />Mark {unpaid.length} unpaid earnings paid</Button></div>
  </Card>;
}
