server {
    listen 127.0.0.1:9471;
    server_name localhost;
    access_log off;
    location = /nginx-status { stub_status; }
    location = /fpm-status {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /fpm-status;
        fastcgi_pass unix:/run/php/repro-monitor-status.sock;
    }
    location / { return 404; }
}
