import React from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { ServiceSelectionDialog } from '@/components/booking/ServiceSelectionDialog';
import type { ServicePackage } from '@/pages/bookShootModel';
import { formatPrice } from '@/utils/servicePricing';
import { UnitManagerDialog } from './UnitManagerDialog';
import { useBookingUnits } from './useMultiUnitBooking';
import { draftUnitKey, linePrice } from './model';

export function BookingUnitManager({ photographers = [] }: { photographers?: Array<{ id: string; name: string }> }) {
  const units = useBookingUnits();
  if (!units?.enabled) return null;
  return <UnitManagerDialog open={units.managerOpen} onClose={() => units.setManagerOpen(false)} units={units.draft.units} onChange={units.changeUnits} activeUnitId={units.draft.activeUnitKey} onSelect={units.setActiveUnit} errors={units.errors}
    renderUnitExtra={unit => <span className="block text-xs text-muted-foreground">{units.draft.lines.filter(line => line.unit_client_key === draftUnitKey(unit)).length} services · {formatPrice(units.draft.lines.filter(line => line.unit_client_key === draftUnitKey(unit)).reduce((sum, line) => sum + linePrice(line, unit, units.catalog), 0))}</span>}
    renderEditorExtra={unit => <div className="space-y-3 border-t pt-3"><h3 className="text-sm font-semibold">Visit overrides</h3><p className="text-xs text-muted-foreground">Leave blank to use shared assignments and sequential service times. Changes here are saved immediately.</p>{units.draft.lines.filter(line => line.unit_client_key === draftUnitKey(unit)).map(line => {
      const resolved = units.schedule.lines.find(item => item.client_key === line.client_key);
      return <div key={line.client_key} className="space-y-2 rounded-lg border p-3"><p className="text-sm font-medium">{units.catalog.find(service => service.id === line.service_id)?.name}</p><p className="text-xs text-muted-foreground">{resolved?.scheduled_date} {resolved?.start_time}–{resolved?.end_time} · {resolved?.duration || 'Missing'} min</p><div className="grid gap-2 sm:grid-cols-2"><div><Label>Date override</Label><Input aria-label={`Date override ${line.service_id}`} type="date" value={line.date ?? ''} onChange={event => units.updateLine(line.client_key, { date: event.target.value || undefined })} /></div><div><Label>Time override</Label><Input aria-label={`Time override ${line.service_id}`} type="time" value={line.time ?? ''} onChange={event => units.updateLine(line.client_key, { time: event.target.value || undefined })} /></div></div><select aria-label={`Photographer override ${line.service_id}`} className="h-10 w-full rounded-md border bg-background px-2 text-sm" value={line.photographer_id ?? ''} onChange={event => units.updateLine(line.client_key, { photographer_id: event.target.value || undefined })}><option value="">Shared photographer</option>{photographers.map(person => <option key={person.id} value={person.id}>{person.name}</option>)}</select></div>;
    })}</div>} />;
}
export function BookingUnitsPropertyControl() {
  const units = useBookingUnits();
  if (!units?.allowed) return null;
  if (!units.enabled) return <label className="flex items-center gap-2 text-sm"><input type="checkbox" className="h-4 w-4 accent-blue-600" checked={false} onChange={units.enable} />Several units or common areas at this address</label>;
  return <div className="rounded-lg border bg-background p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><strong className="text-sm">{units.draft.units.length} units and common areas</strong><p className="text-xs text-muted-foreground">{Object.keys(units.errors).length} need attention · dimensions and access are per unit</p></div><Button type="button" variant="outline" onClick={() => units.setManagerOpen(true)}>Manage units</Button></div></div>;
}
export function BookingUnitsSummary() {
  const units = useBookingUnits();
  if (!units?.enabled) return null;
  return <div className="my-3 rounded-lg border border-blue-200 bg-blue-50/50 p-3 dark:border-blue-900 dark:bg-blue-950/20"><div className="flex flex-wrap items-center justify-between gap-2"><strong className="text-sm">{units.draft.units.length} units · {units.draft.lines.length} service lines</strong><Button size="sm" variant="ghost" onClick={() => units.setManagerOpen(true)}>View breakdown</Button></div>{Object.keys(units.errors).length > 0 && <p className="text-xs text-destructive">{Object.keys(units.errors).length} units need attention.</p>}</div>;
}
export function BookingUnitsScheduleNotice() {
  const units = useBookingUnits();
  if (!units?.enabled) return null;
  const overrides = units.draft.lines.filter(line => line.date || line.time || line.photographer_id).length;
  return <div className="space-y-2 rounded-xl border bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">{units.draft.units.length} units · {Math.round(units.schedule.totalMinutes)} minutes of work</h3><p className="text-xs text-muted-foreground">Default assignments below cover all units. Each photographer’s services run sequentially; {overrides} line overrides.</p></div><Button variant="outline" onClick={() => units.setManagerOpen(true)}>Visit details &amp; overrides</Button></div>{units.schedule.errors.length > 0 && <p className="text-sm text-destructive">{units.schedule.errors[0]}{units.schedule.errors.length > 1 ? ` (${units.schedule.errors.length} issues across the booking)` : ''}</p>}<p className="text-xs text-muted-foreground">Full occupied blocks are checked on confirmation. Split work across dates when it exceeds a photographer’s availability.</p></div>;
}
export function MultiUnitServicesStep({ onBack, onContinue, notes, setNotes, packagesLoading }: { onBack: () => void; onContinue: () => void; notes: string; setNotes: (value: string) => void; packagesLoading: boolean }) {
  const units = useBookingUnits()!;
  const [catalogOpen, setCatalogOpen] = React.useState(false);
  const [copyOpen, setCopyOpen] = React.useState(false);
  const [selected, setSelected] = React.useState<Set<string>>(new Set());
  const [query, setQuery] = React.useState('');
  const [page, setPage] = React.useState(0);
  const u = units.activeUnit;
  if (!u) return <Button onClick={() => units.setManagerOpen(true)}>Add units</Button>;
  const targets = units.draft.units.filter(unit => unit.client_key !== u.client_key && unit.label.toLowerCase().includes(query.toLowerCase()));
  const rows = targets.slice(page * 8, page * 8 + 8);
  const toggle = (key: string) => setSelected(current => { const next = new Set(current); if (next.has(key)) next.delete(key); else next.add(key); return next; });
  return <div className="space-y-4"><div className="flex min-w-0 flex-wrap items-center justify-between gap-3 rounded-xl border border-primary/30 bg-primary/5 p-3"><div className="min-w-0"><p className="text-xs text-muted-foreground">Services for</p><strong className="block truncate">{u.label} · {u.sqft?.toLocaleString()} sqft</strong></div><Button variant="outline" onClick={() => units.setManagerOpen(true)}>Change unit</Button></div><div className="rounded-2xl border bg-card p-4 sm:p-5"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">Selected services</h3><Button onClick={() => setCatalogOpen(true)}>Select services</Button></div><div className="mt-3 space-y-2">{units.activeServices.map(service => <div key={service.id} className="flex justify-between gap-3 rounded-lg border p-3 text-sm"><span className="min-w-0 break-words">{service.name}</span><div className="flex shrink-0 items-center gap-2"><strong>{formatPrice(linePrice(units.draft.lines.find(line => line.unit_client_key === u.client_key && line.service_id === service.id)!, u, units.catalog))}</strong><Button size="sm" variant="ghost" aria-label={`Remove ${service.name}`} onClick={() => units.changeServices(units.activeServices.filter(item => item.id !== service.id))}>×</Button></div></div>)}{!units.activeServices.length && <p className="text-sm text-muted-foreground">Select services for this unit.</p>}</div><Button variant="link" className="mt-2 px-0" disabled={!units.activeServices.length} onClick={() => { setSelected(new Set()); setQuery(''); setPage(0); setCopyOpen(true); }}>Copy services to units…</Button></div><div className="space-y-3 rounded-2xl border bg-card p-4"><Label>Access for {u.label}</Label><p className="whitespace-pre-wrap text-sm text-muted-foreground">{u.access_notes || 'No access notes yet.'}</p><Button variant="outline" onClick={() => units.setManagerOpen(true)}>Edit unit access</Button><Label htmlFor="unit-shared-notes">Shoot notes · shared</Label><Textarea id="unit-shared-notes" value={notes} onChange={event => setNotes(event.target.value)} /></div><BookingUnitsSummary /><div className="flex justify-between"><Button variant="outline" onClick={onBack}>Back</Button><Button onClick={onContinue}>Continue</Button></div>
    <ServiceSelectionDialog open={catalogOpen} onOpenChange={setCatalogOpen} services={units.visibleCatalog} selectedServices={units.activeServices} onSelectedServicesChange={value => units.changeServices(value as ServicePackage[])} servicesLoading={packagesLoading} effectiveSqft={u.sqft} description={`Services for ${u.label}. Prices use this unit’s square footage.`} allowEmptySelection />
    <Dialog open={copyOpen} onOpenChange={setCopyOpen}><DialogContent className="flex max-h-[84dvh] max-w-xl flex-col"><DialogHeader><DialogTitle>Copy services to units</DialogTitle><DialogDescription>Adds missing services, priced using each destination’s SQFT. Existing choices, prices and visit overrides stay intact.</DialogDescription></DialogHeader><div className="min-h-0 flex-1 space-y-3 overflow-y-auto"><Input aria-label="Search target units" value={query} onChange={event => { setQuery(event.target.value); setPage(0); }} placeholder="Search units…" /><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => setSelected(current => new Set([...current, ...rows.map(unit => unit.client_key)]))}>Select this page</Button><Button size="sm" variant="outline" onClick={() => setSelected(current => new Set([...current, ...targets.map(unit => unit.client_key)]))}>Select all matching</Button><Button size="sm" variant="ghost" onClick={() => setSelected(new Set())}>Clear</Button></div>{rows.map(unit => <label key={unit.client_key} className="flex items-center gap-3 border-b py-3 text-sm"><input type="checkbox" checked={selected.has(unit.client_key)} onChange={() => toggle(unit.client_key)} /><span className="min-w-0 break-words">{unit.label} · {unit.sqft?.toLocaleString()} sqft</span></label>)}<div className="flex items-center justify-between gap-2"><span className="text-xs">{targets.length ? page * 8 + 1 : 0}–{Math.min(page * 8 + 8, targets.length)} of {targets.length}</span><div className="flex gap-1"><Button size="sm" variant="outline" disabled={!page} onClick={() => setPage(page - 1)}>Previous</Button><Button size="sm" variant="outline" disabled={(page + 1) * 8 >= targets.length} onClick={() => setPage(page + 1)}>Next</Button></div></div></div><div className="flex flex-wrap items-center justify-between gap-2 border-t pt-3"><span className="text-sm">{selected.size} selected</span><Button disabled={!selected.size} onClick={() => { units.copyServices([...selected]); setCopyOpen(false); }}>Add missing services</Button></div></DialogContent></Dialog>
  </div>;
}
