import type { ShootData, ShootServiceObject } from '@/types/shoots';

export type ApiNotePayload = {
  shootNotes?: string;
  approvalNotes?: string;
  approval_notes?: string;
  photographerNotes?: string;
  companyNotes?: string;
  editingNotes?: string;
};

export type ApiShootPayment = {
  amount?: unknown;
  paid_at?: string;
};

type ApiGhostUser = {
  id?: string | number;
  name?: string;
  email?: string;
  company?: string;
  company_name?: string;
};

type ApiServiceRange = {
  id?: string | number;
  sqft_from?: number;
  sqft_to?: number;
  duration?: number | null;
  price?: number;
  photographer_pay?: number | null;
  photo_count?: number | null;
};

export type ApiServiceRecord = {
  id?: string | number;
  service_id?: string | number | null;
  serviceId?: string | number | null;
  shoot_service_id?: string | number | null;
  shootServiceId?: string | number | null;
  name?: string;
  service_name?: string;
  serviceName?: string;
  label?: string;
  price?: number;
  subtotal?: number;
  quantity?: number;
  photo_count?: number | null;
  photoCount?: number | null;
  pricing_type?: 'fixed' | 'variable';
  sqft_ranges?: ApiServiceRange[];
  sqftRanges?: ApiServiceRange[];
  category?: ShootServiceObject['category'];
  category_name?: string;
  photographer_pay?: number | null;
  photographerPay?: number | null;
  photographer_id?: string | number | null;
  photographerId?: string | number | null;
  resolved_photographer_id?: string | number | null;
  resolvedPhotographerId?: string | number | null;
  photographer?: unknown;
  resolved_photographer?: unknown;
  resolved_photographer_name?: string;
  photographer_name?: string;
  editor_id?: string | number | null;
  editorId?: string | number | null;
  resolved_editor_id?: string | number | null;
  resolvedEditorId?: string | number | null;
  editor?: unknown;
  resolved_editor?: unknown;
  resolved_editor_name?: string;
  editor_name?: string;
  editing_completed_at?: string | null;
  scheduled_at?: string | null;
  scheduledAt?: string | null;
  workflow_status?: string | null;
  workflowStatus?: string | null;
  delivery_status?: string | null;
  deliveryStatus?: string | null;
  ready_at?: string | null;
  readyAt?: string | null;
  delivered_at?: string | null;
  deliveredAt?: string | null;
  is_deliverable?: boolean;
  isDeliverable?: boolean;
  paid_amount?: number;
  paidAmount?: number;
  balance_due?: number;
  balanceDue?: number;
  payment_status?: string | null;
  paymentStatus?: string | null;
  force_unlock_delivery?: boolean;
  forceUnlockDelivery?: boolean;
  is_unlocked_for_delivery?: boolean;
  isUnlockedForDelivery?: boolean;
  unlock_state?: string;
  unlockState?: string;
  lane?: string | null;
  category_key?: string | null;
  categoryKey?: string | null;
  service?: ApiServiceRecord;
  pivot?: ApiServiceRecord;
  [key: string]: unknown;
};

export type ApiShoot = {
  id?: string | number;
  scheduled_date?: string;
  time?: string;
  client?: {
    id?: string | number;
    name?: string;
    email?: string;
    email_verified?: boolean;
    emailVerified?: boolean;
    company_name?: string;
    phone?: string;
    phonenumber?: string;
    total_shoots?: number;
    rep?: {
      id?: string | number;
      name?: string;
      avatar?: string;
      email?: string;
      phone?: string;
      phonenumber?: string;
    } | null;
  } | null;
  client_shoots_count?: number;
  photographer?: {
    id?: string | number;
    name?: string;
    avatar?: string;
    email?: string;
    phone?: string;
    phonenumber?: string;
  } | null;
  rep?: {
    id?: string | number;
    name?: string;
    avatar?: string;
    email?: string;
    phone?: string;
    phonenumber?: string;
  } | null;
  editor?: {
    id?: string | number;
    name?: string;
    avatar?: string;
    email?: string;
  } | null;
  service?: {
    name?: string;
  } | null;
  services?: Array<string | ApiServiceRecord>;
  serviceItems?: ApiServiceRecord[];
  service_items?: ApiServiceRecord[];
  /** Display-only names for every booked service; never role-filtered. */
  servicePresentation?: Array<Record<string, unknown>>;
  service_presentation?: Array<Record<string, unknown>>;
  services_list?: string[];
  address?: string;
  address2?: string;
  city?: string;
  state?: string;
  zip?: string;
  payments?: ApiShootPayment[];
  base_quote?: unknown;
  tax_rate?: unknown;
  tax_percent?: unknown;
  taxPercent?: unknown;
  tax_amount?: unknown;
  total_quote?: unknown;
  total_paid?: unknown;
  payment_type?: string;
  status?: string;
  workflow_status?: string;
  workflowStatus?: string;
  canSubmitRaw?: boolean;
  canSubmitEdits?: boolean;
  canViewInvoice?: boolean;
  canFinalizeNoMedia?: boolean;
  canRemoveAllServices?: boolean;
  can_submit_raw?: boolean;
  can_submit_edits?: boolean;
  can_view_invoice?: boolean;
  can_finalize_no_media?: boolean;
  can_remove_all_services?: boolean;
  notes?: string | ApiNotePayload | null;
  shoot_notes?: string;
  approval_notes?: string;
  approvalNotes?: string;
  photographer_notes?: string;
  company_notes?: string;
  editor_notes?: string;
  admin_issue_notes?: string;
  is_flagged?: boolean;
  issues_resolved_at?: string;
  issues_resolved_by?: string | number;
  submitted_for_review_at?: string;
  created_by?: string;
  completed_date?: string;
  completed_at?: string;
  editing_completed_at?: string;
  admin_verified_at?: string;
  expected_final_count?: number;
  expected_raw_count?: number;
  raw_photo_count?: number;
  edited_photo_count?: number;
  extra_photo_count?: number;
  media?: ShootData['media'];
  tour_links?: ShootData['tourLinks'];
  files?: ShootData['files'];
  tour_purchased?: unknown;
  is_private_listing?: boolean;
  isPrivateListing?: boolean;
  is_featured?: boolean;
  isFeatured?: boolean;
  featured_pending?: boolean;
  featuredPending?: boolean;
  featured_status?: string;
  featuredStatus?: string;
  ghost_users?: ApiGhostUser[];
  ghostUsers?: ApiGhostUser[];
  ghost_user_ids?: Array<string | number>;
  ghostUserIds?: Array<string | number>;
  is_ghost_visible_for_user?: boolean;
  isGhostVisibleForUser?: boolean;
  service_subtotal?: unknown;
  serviceSubtotal?: unknown;
  discount_type?: unknown;
  discountType?: unknown;
  discount_value?: unknown;
  discountValue?: unknown;
  discount_amount?: unknown;
  discountAmount?: unknown;
  discounted_subtotal?: unknown;
  discountedSubtotal?: unknown;
  invoice_adjustments_total?: unknown;
  invoiceAdjustmentsTotal?: unknown;
  order_total?: unknown;
  orderTotal?: unknown;
  overpayment_amount?: unknown;
  overpaymentAmount?: unknown;
  payment?: {
    serviceSubtotal?: unknown;
    service_subtotal?: unknown;
    baseQuote?: unknown;
    base_quote?: unknown;
    discountType?: unknown;
    discount_type?: unknown;
    discountValue?: unknown;
    discount_value?: unknown;
    discountAmount?: unknown;
    discount_amount?: unknown;
    discountedSubtotal?: unknown;
    discounted_subtotal?: unknown;
    taxRate?: unknown;
    tax_rate?: unknown;
    taxPercent?: unknown;
    tax_percent?: unknown;
    taxAmount?: unknown;
    tax_amount?: unknown;
    invoiceAdjustmentsTotal?: unknown;
    invoice_adjustments_total?: unknown;
    orderTotal?: unknown;
    order_total?: unknown;
    totalQuote?: unknown;
    total_quote?: unknown;
    totalPaid?: unknown;
    total_paid?: unknown;
    overpaymentAmount?: unknown;
    overpayment_amount?: unknown;
    paymentStatus?: unknown;
    payment_status?: unknown;
  };
  editor_id?: string | number;
  editorId?: string | number;
  editor_assignments?: unknown[];
  editorAssignments?: unknown[];
  scheduled_at?: string;
  scheduledAt?: string;
  scheduledDate?: string;
  photographer_email?: string;
  photographerEmail?: string;
  photographer_phone?: string;
  photographerPhone?: string;
  salesRep?: unknown;
  sales_rep?: unknown;
  shoot_type?: string;
  shootType?: string;
  reshoot_parent?: ShootData['reshootParent'];
  reshootParent?: ShootData['reshootParent'];
  reshoot_root?: ShootData['reshootRoot'];
  reshootRoot?: ShootData['reshootRoot'];
  reshoot_children?: ShootData['reshootChildren'];
  reshootChildren?: ShootData['reshootChildren'];
  reshoot_reason_code?: string | null;
  reshootReasonCode?: string | null;
  reshoot_reason_note?: string | null;
  reshootReasonNote?: string | null;
  reshoot_service_links?: ShootData['reshootServiceLinks'];
  reshootServiceLinks?: ShootData['reshootServiceLinks'];
  compensation_summary?: Record<string, unknown> | null;
  compensationSummary?: Record<string, unknown> | null;
  bracket_mode?: number | null;
  bracketMode?: number | null;
  hero_image?: string;
  heroImage?: string;
  iguide_tour_url?: string;
  iguide_floorplans?: ShootData['iguideFloorplans'];
  iguide_property_id?: string;
  iguide_work_order_id?: string;
  iguide_last_synced_at?: string;
  iguide_data?: ShootData['iguideData'];
  iguide_manual_offline_package?: ShootData['iguideManualOfflinePackage'];
  cubicasa_tour_url?: string;
  cubicasa_floorplans?: ShootData['cubicasaFloorplans'];
  cubicasa_data?: ShootData['cubicasaData'];
  cubicasa_status?: string;
  cubicasa_product_type?: string;
  cubicasa_order_id?: string | number;
  cubicasa_external_id?: string | number;
  cubicasa_last_synced_at?: string;
  featuredRequestedAt?: string | null;
  featured_requested_at?: string | null;
  featuredRequestedBy?: string | number | null;
  featured_requested_by?: string | number | null;
  featuredApprovedAt?: string | null;
  featured_approved_at?: string | null;
  featuredApprovedBy?: string | number | null;
  featured_approved_by?: string | number | null;
  total_photographer_pay?: number;
  property_details?: ShootData['propertyDetails'];
  cancellationRequestedAt?: string;
  cancellation_requested_at?: string;
  cancellationReason?: string;
  cancellation_reason?: string;
  holdRequestedAt?: string;
  hold_requested_at?: string;
  holdRequestedBy?: string | number;
  hold_requested_by?: string | number;
  holdReason?: string;
  hold_reason?: string;
  mmm_status?: string;
  mmm_order_number?: string;
  mmm_buyer_cookie?: string;
  mmm_redirect_url?: string;
  mmm_last_punchout_at?: string;
  mmm_last_order_at?: string;
  mmm_last_error?: string;
  alternate_scheduled_date?: string | null;
  alternateScheduledDate?: string | null;
  alternate_time?: string | null;
  alternateTime?: string | null;
  alternate_scheduled_at?: string | null;
  alternateScheduledAt?: string | null;
  requested_photographers?: ShootData['requested_photographers'];
  requestedPhotographers?: ShootData['requested_photographers'];
  external_booking_payload?: ShootData['external_booking_payload'];
  externalBookingPayload?: ShootData['external_booking_payload'];
  external_booking_warnings?: ShootData['external_booking_warnings'];
  externalBookingWarnings?: ShootData['external_booking_warnings'];
  external_booking_mapping_status?: string | null;
  externalBookingMappingStatus?: string | null;
  [key: string]: unknown;
};
