// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://necyyfxufhmacccbhkdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lY3l5Znh1ZmhtYWNjY2Joa2RtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0OTE2NDgsImV4cCI6MjA1ODA2NzY0OH0.6WEsTF9auVNvmU2is_h03X1BiL3bFbnkEQZt3PdRhIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);